[MFLOG|0|2025-01-05T09:20:16.865044Z|runtime|f195eab8-8e9d-4fc8-bacf-7b7e6fe4e3e1]<flow ClusteringFlow step start> failed:
[MFLOG|0|2025-01-05T09:20:16.869398Z|runtime|71b55bc5-957c-4dd4-b1fc-2c2bd2ebb372]    Internal error
[MFLOG|0|2025-01-05T09:20:16.870424Z|runtime|16bbc1e7-a0ef-490e-b35b-5458edd0b8a1]Traceback (most recent call last):
[MFLOG|0|2025-01-05T09:20:16.870471Z|runtime|f9128acf-b50e-48fd-b5d2-cc5bd8953673]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/cli.py", line 629, in main
[MFLOG|0|2025-01-05T09:20:16.870504Z|runtime|483dfb96-c447-4c49-9284-cc9bee03a065]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-01-05T09:20:16.870537Z|runtime|0bf15cba-4617-4d78-952b-87d39b65749a]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-01-05T09:20:16.870566Z|runtime|ae26a7c6-be91-4219-bb61-f24cc9c416ca]    return self.main(args, kwargs)
[MFLOG|0|2025-01-05T09:20:16.976422Z|runtime|370e35c7-c48e-4d58-b13f-0934223d74a5]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-01-05T09:20:16.976580Z|runtime|47d5ba25-8203-47bb-94f7-8dc1a8bf7b76]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-01-05T09:20:16.976618Z|runtime|83ff4a6c-13c8-4ab4-b4f3-9afa01cbfc26]    rv = self.invoke(ctx)
[MFLOG|0|2025-01-05T09:20:16.976653Z|runtime|f598455f-d3c8-495b-9bc2-c9802210d357]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2025-01-05T09:20:16.976680Z|runtime|404fb296-8885-4eb7-92f8-97c1ab843b50]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-01-05T09:20:16.976715Z|runtime|6116804e-8cee-4ea3-bdd2-566ae7130f9c]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-01-05T09:20:16.976736Z|runtime|07383926-e4d7-4793-9313-d49f58b44325]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-01-05T09:20:16.976759Z|runtime|b24ba415-018d-4381-8615-659f0ee96b35]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-01-05T09:20:16.976787Z|runtime|078d394c-6f89-49f8-9cdf-ab8a1eb3d4f1]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-01-05T09:20:16.976818Z|runtime|1f500d93-9c07-4e6b-9318-0c93c01fb4de]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-01-05T09:20:16.976842Z|runtime|7c733053-0c02-4d6f-9f7a-d0f5a0c1d9e4]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-01-05T09:20:16.976868Z|runtime|fd44b571-d469-456e-a61b-2a62e666dd8f]    return callback(args, kwargs)
[MFLOG|0|2025-01-05T09:20:16.976892Z|runtime|51886da9-697e-4cc2-a01c-7730c7f0d96c]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-01-05T09:20:16.976916Z|runtime|3d871c84-b142-493e-9fef-8c775c73cdbd]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-01-05T09:20:16.976949Z|runtime|c60b3371-ba68-43c9-86a6-7904b9a73ddd]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-01-05T09:20:16.976974Z|runtime|a606fa3e-6a3b-41ff-8b71-b932e1d18c99]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-01-05T09:20:16.976996Z|runtime|ceea3f3b-85b3-4cb5-9fa7-9b31a4020248]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 178, in step
[MFLOG|0|2025-01-05T09:20:16.977019Z|runtime|dcc66e01-c42b-4085-84aa-b663d53b3000]    task.run_step(
[MFLOG|0|2025-01-05T09:20:16.977042Z|runtime|b50a3958-98b2-4058-bbc5-e6c4cc65a71b]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/task.py", line 653, in run_step
[MFLOG|0|2025-01-05T09:20:16.977068Z|runtime|9182809f-c2e7-43a7-8ffe-ca0bf152895a]    self._exec_step_function(step_func)
[MFLOG|0|2025-01-05T09:20:16.977090Z|runtime|dab4d203-4291-4d5a-bf3c-b0b29eb13c67]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/myenv/lib/python3.12/site-packages/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2025-01-05T09:20:16.977112Z|runtime|b8c5386d-bdcb-49ca-ab72-828e2f714df7]    step_function()
[MFLOG|0|2025-01-05T09:20:16.977134Z|runtime|554d703c-ba71-4c7f-9632-7509efe3e4ac]  File "/Users/dimasrizki/Documents/ipsd/L196_Tugas Sebelum UAS/many_kmeans_flow.py", line 30, in start
[MFLOG|0|2025-01-05T09:20:16.977160Z|runtime|4a6b20f5-cc06-4f01-a5fc-25e30416c997]    raise ValueError("Dataset must contain numeric columns for clustering.")
[MFLOG|0|2025-01-05T09:20:16.977182Z|runtime|75c7e479-0e36-428e-b344-26d89aa93adb]ValueError: Dataset must contain numeric columns for clustering.
[MFLOG|0|2025-01-05T09:20:16.977205Z|runtime|0c36cdaf-ad7f-41f8-821b-d9c1842f17d2]
[MFLOG|0|2025-01-05T09:20:16.977612Z|runtime|52e56c6c-0df5-4a6d-a35e-c9460f8ef242]Task failed.